### ISSUE TITLE
Support for unzipping Password protected files

### ISSUE THREAD

**Issue by Akeelahamed17** [FBoucher/AzUnzipEverything#19]
Would love the ability to unzip password protected files especially AES encrypted.

**Comment by mreyeros** [comment]
Would the assumption here be that all of the zip files are protected with the same password?  Additionally, would the password(s) be stored in Azure KeyVault?  Lastly, any issue with using a 3rd party library that can decompress password protected files since I do not believe that the System.IO.Compresion library provides this capability?

**Comment by FBoucher** [comment]
@mreyeros as long as it's free for all to use.
:)

**Comment by mreyeros** [comment]
Yes sir the library that I used was DotNetZip, which I believe is under Microsoft Public License, MS-PL

**Comment by Nighathp** [comment]
> Would love the ability to unzip password protected files especially AES encrypted.

Hi Akeel, I have a similar requirement. Were you able to retrieve the password from keyvault and apply the password to the password protected file ?

**Comment by Akeelahamed17** [comment]
Hi, 

Yes! I used python for this and was able to successfully also use key vault for the password. 
Let me know if you would like me to share the code and I can post on GitHub.

Kind Regards

Akeel Ahamed 
Data Analyst 
Optalitix Ltd 
+447366706777

**Comment by Nighathp** [comment]
Hi Akeel,

Thanks so much for your quick reply...
Please could you take a look at my requirement and advise accordingly ?

An incremental data set is generated nightly from the source system, zipped, password protected/encrypted and then uploaded into an AWS cloud data storage repository (S3 storage)

A trigger executes an Azure Data Factory pipeline DataLoadv2 that:
1.     Calls an Azure Function, that executes a PowerShell script(from Azure function  FileCheckAndLoad) script:
a)     Downloads the encrypted file from the S3 Bucket;
b)     Decrypts the file; and
c)     Copies the file to an Azure Storage container.
 
2.     A Copy activity moves the file from Azure Storage to an on-premises network location.
 
The file is then used by an SSIS process that integrates the data into the target database.
 
excerpt from Azure function(  FileCheckAndLoad )
------------------------------------
 .....
-----
------
 
# Decrypt the file
$EncryptedFile = $MyFolder + $LocalFileName
$OutputFile = $MyFolder + $LocalFileName.replace(".gpg", "_")
 
$GPGExe = $GPGFolder + "bin\gpg.exe"
 
#$GPGArgs = "-d -o {0} --batch {1}" -f $OutputFile, $EncryptedFile
$GPGArgs = "-v --batch --output {0} --decrypt {1}" -f $OutputFile, $EncryptedFile   <-- decryption happening here 
 
if (-not (Test-Path $OutputFile)) {
Write-Output $("Starting decryption with args: " + $GPGArgs)
Start-Process $GPGExe -ArgumentList $GPGArgs -Wait -NoNewWindow
Write-Output $("File decrypted: " + $OutputFile)
}
 
#This portion establishes a connection to the Azure storage and copies the decrypted files.
$ConnectionString = $env:APPSETTING_AZ_STRG_CON
$Ctx = New-AzureStorageContext -ConnectionString $ConnectionString
$ContainerName  = "pcblb"
# $Folder = "Myfiles/"
# $Folder = "mytestfiles/" # TEST ONLY
$ProgressPreference = "SilentlyContinue"
 
The  above portion decrypts the file and the below portion establishes the connection with Azure storage and copies the files to it.
 
Now I want the decryption to happen by retrieving the password from the key vault(instead of direct encryption) and using it to decrypt the file before its copied to the Azure storage.

Please could you advise?

**Comment by FBoucher** [comment]
merged
